version: '3'

services:
  postgres:
    image: postgres:10
    volumes:
      - .pgdata:/var/lib/postgresql/data
    env_file: .env
    build:
      context: ./postgres
  web:
    build: ./sendero_unillanos
    container_name: sendero_unillanos
    depends_on:
      - postgres
    env_file: .env
    command: gunicorn -b :9000 -w 3 sendero_unillanos.wsgi:application --reload --timeout 3600
    volumes:
      - ./sendero_unillanos:/code
    #ports:
    #  - "8000:8000"
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    volumes:
      - ./sendero_unillanos/sendero_unillanos/static:/static
      - ./sendero_unillanos/sendero_unillanos/media:/media
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
