from django.db import models

# Create your models here.
from singleton_model import SingletonModel


class Sendero(SingletonModel):
    titulo = models.CharField(max_length=500)
    banner = models.ImageField(null=True, blank=True)

    img_seccion1 = models.ImageField(blank=True, null=True)
    ref_img_seccion1 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion1 = models.CharField(max_length=500)
    parrafo1_seccion1 = models.CharField(max_length=2000)
    subtitulo2_seccion1 = models.CharField(max_length=500)
    parrafo2_seccion1 = models.CharField(max_length=2000)
    subtitulo3_seccion1 = models.CharField(max_length=500)
    parrafo3_seccion1 = models.CharField(max_length=2000)
    subtitulo4_seccion1 = models.CharField(max_length=500)
    parrafo4_seccion1 = models.CharField(max_length=2000)
    subtitulo5_seccion1 = models.CharField(max_length=500)
    parrafo5_seccion1 = models.CharField(max_length=2000)
    subtitulo6_seccion1 = models.CharField(max_length=500)
    parrafo6_seccion1 = models.CharField(max_length=2000)
    img_tabla_seccion1 = models.ImageField(blank=True, null=True)

    img_seccion2 = models.ImageField(blank=True, null=True)
    ref_img_seccion2 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion2 = models.CharField(max_length=500)
    parrafo1_seccion2 = models.CharField(max_length=2000)
    subtitulo2_seccion2 = models.CharField(max_length=500)
    parrafo2_seccion2 = models.CharField(max_length=2000)
    subtitulo3_seccion2 = models.CharField(max_length=500)
    parrafo3_seccion2 = models.CharField(max_length=2000)
    subtitulo4_seccion2 = models.CharField(max_length=500)
    parrafo4_seccion2 = models.CharField(max_length=2000)
    subtitulo5_seccion2 = models.CharField(max_length=500)
    parrafo5_seccion2 = models.CharField(max_length=2000)
    subtitulo6_seccion2 = models.CharField(max_length=500)
    parrafo6_seccion2 = models.CharField(max_length=2000)
    img_tabla_seccion2 = models.ImageField(blank=True, null=True)

    img_seccion3 = models.ImageField(blank=True, null=True)
    ref_img_seccion3 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion3 = models.CharField(max_length=500)
    parrafo1_seccion3 = models.CharField(max_length=2000)
    subtitulo2_seccion3 = models.CharField(max_length=500)
    parrafo2_seccion3 = models.CharField(max_length=2000)
    subtitulo3_seccion3 = models.CharField(max_length=500)
    parrafo3_seccion3 = models.CharField(max_length=2000)
    subtitulo4_seccion3 = models.CharField(max_length=500)
    parrafo4_seccion3 = models.CharField(max_length=2000)
    subtitulo5_seccion3 = models.CharField(max_length=500)
    parrafo5_seccion3 = models.CharField(max_length=2000)
    subtitulo6_seccion3 = models.CharField(max_length=500)
    parrafo6_seccion3 = models.CharField(max_length=2000)
    img_tabla_seccion3 = models.ImageField(blank=True, null=True)

    img_seccion4 = models.ImageField(blank=True, null=True)
    ref_img_seccion4 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion4 = models.CharField(max_length=500)
    parrafo1_seccion4 = models.CharField(max_length=2000)
    subtitulo2_seccion4 = models.CharField(max_length=500)
    parrafo2_seccion4 = models.CharField(max_length=2000)
    subtitulo3_seccion4 = models.CharField(max_length=500)
    parrafo3_seccion4 = models.CharField(max_length=2000)
    subtitulo4_seccion4 = models.CharField(max_length=500)
    parrafo4_seccion4 = models.CharField(max_length=2000)
    subtitulo5_seccion4 = models.CharField(max_length=500)
    parrafo5_seccion4 = models.CharField(max_length=2000)
    subtitulo6_seccion4 = models.CharField(max_length=500)
    parrafo6_seccion4 = models.CharField(max_length=2000)
    img_tabla_seccion4 = models.ImageField(blank=True, null=True)

    img_seccion5 = models.ImageField(blank=True, null=True)
    ref_img_seccion5 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion5 = models.CharField(max_length=500)
    parrafo1_seccion5 = models.CharField(max_length=2000)
    subtitulo2_seccion5 = models.CharField(max_length=500)
    parrafo2_seccion5 = models.CharField(max_length=2000)
    subtitulo3_seccion5 = models.CharField(max_length=500)
    parrafo3_seccion5 = models.CharField(max_length=2000)
    subtitulo4_seccion5 = models.CharField(max_length=500)
    parrafo4_seccion5 = models.CharField(max_length=2000)
    subtitulo5_seccion5 = models.CharField(max_length=500)
    parrafo5_seccion5 = models.CharField(max_length=2000)
    subtitulo6_seccion5 = models.CharField(max_length=500)
    parrafo6_seccion5 = models.CharField(max_length=2000)
    img_tabla_seccion5 = models.ImageField(blank=True, null=True)

    img_seccion6 = models.ImageField(blank=True, null=True)
    ref_img_seccion6 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion6 = models.CharField(max_length=500)
    parrafo1_seccion6 = models.CharField(max_length=2000)
    subtitulo2_seccion6 = models.CharField(max_length=500)
    parrafo2_seccion6 = models.CharField(max_length=2000)
    subtitulo3_seccion6 = models.CharField(max_length=500)
    parrafo3_seccion6 = models.CharField(max_length=2000)
    subtitulo4_seccion6 = models.CharField(max_length=500)
    parrafo4_seccion6 = models.CharField(max_length=2000)
    subtitulo5_seccion6 = models.CharField(max_length=500)
    parrafo5_seccion6 = models.CharField(max_length=2000)
    subtitulo6_seccion6 = models.CharField(max_length=500)
    parrafo6_seccion6 = models.CharField(max_length=2000)
    img_tabla_seccion6 = models.ImageField(blank=True, null=True)

    img_seccion7 = models.ImageField(blank=True, null=True)
    ref_img_seccion7 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion7 = models.CharField(max_length=500)
    parrafo1_seccion7 = models.CharField(max_length=2000)
    subtitulo2_seccion7 = models.CharField(max_length=500)
    parrafo2_seccion7 = models.CharField(max_length=2000)
    subtitulo3_seccion7 = models.CharField(max_length=500)
    parrafo3_seccion7 = models.CharField(max_length=2000)
    subtitulo4_seccion7 = models.CharField(max_length=500)
    parrafo4_seccion7 = models.CharField(max_length=2000)
    subtitulo5_seccion7 = models.CharField(max_length=500)
    parrafo5_seccion7 = models.CharField(max_length=2000)
    subtitulo6_seccion7 = models.CharField(max_length=500)
    parrafo6_seccion7 = models.CharField(max_length=2000)
    img_tabla_seccion7 = models.ImageField(blank=True, null=True)

    img_seccion8 = models.ImageField(blank=True, null=True)
    ref_img_seccion8 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion8 = models.CharField(max_length=500)
    parrafo1_seccion8 = models.CharField(max_length=2000)
    subtitulo2_seccion8 = models.CharField(max_length=500)
    parrafo2_seccion8 = models.CharField(max_length=2000)
    subtitulo3_seccion8 = models.CharField(max_length=500)
    parrafo3_seccion8 = models.CharField(max_length=2000)
    subtitulo4_seccion8 = models.CharField(max_length=500)
    parrafo4_seccion8 = models.CharField(max_length=2000)
    subtitulo5_seccion8 = models.CharField(max_length=500)
    parrafo5_seccion8 = models.CharField(max_length=2000)
    subtitulo6_seccion8 = models.CharField(max_length=500)
    parrafo6_seccion8 = models.CharField(max_length=2000)
    img_tabla_seccion8 = models.ImageField(blank=True, null=True)

    img_seccion9 = models.ImageField(blank=True, null=True)
    ref_img_seccion9 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion9 = models.CharField(max_length=500)
    parrafo1_seccion9 = models.CharField(max_length=2000)
    subtitulo2_seccion9 = models.CharField(max_length=500)
    parrafo2_seccion9 = models.CharField(max_length=2000)
    subtitulo3_seccion9 = models.CharField(max_length=500)
    parrafo3_seccion9 = models.CharField(max_length=2000)
    subtitulo4_seccion9 = models.CharField(max_length=500)
    parrafo4_seccion9 = models.CharField(max_length=2000)
    subtitulo5_seccion9 = models.CharField(max_length=500)
    parrafo5_seccion9 = models.CharField(max_length=2000)
    subtitulo6_seccion9 = models.CharField(max_length=500)
    parrafo6_seccion9 = models.CharField(max_length=2000)
    img_tabla_seccion9 = models.ImageField(blank=True, null=True)

    img_seccion10 = models.ImageField(blank=True, null=True)
    ref_img_seccion10 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion10 = models.CharField(max_length=500)
    parrafo1_seccion10 = models.CharField(max_length=2000)
    subtitulo2_seccion10 = models.CharField(max_length=500)
    parrafo2_seccion10 = models.CharField(max_length=2000)
    subtitulo3_seccion10 = models.CharField(max_length=500)
    parrafo3_seccion10 = models.CharField(max_length=2000)
    subtitulo4_seccion10 = models.CharField(max_length=500)
    parrafo4_seccion10 = models.CharField(max_length=2000)
    subtitulo5_seccion10 = models.CharField(max_length=500)
    parrafo5_seccion10 = models.CharField(max_length=2000)
    subtitulo6_seccion10 = models.CharField(max_length=500)
    parrafo6_seccion10 = models.CharField(max_length=2000)
    img_tabla_seccion10 = models.ImageField(blank=True, null=True)

    img_seccion11 = models.ImageField(blank=True, null=True)
    ref_img_seccion11 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion11 = models.CharField(max_length=500)
    parrafo1_seccion11 = models.CharField(max_length=2000)
    subtitulo2_seccion11 = models.CharField(max_length=500)
    parrafo2_seccion11 = models.CharField(max_length=2000)
    subtitulo3_seccion11 = models.CharField(max_length=500)
    parrafo3_seccion11 = models.CharField(max_length=2000)
    subtitulo4_seccion11 = models.CharField(max_length=500)
    parrafo4_seccion11 = models.CharField(max_length=2000)
    subtitulo5_seccion11 = models.CharField(max_length=500)
    parrafo5_seccion11 = models.CharField(max_length=2000)
    subtitulo6_seccion11 = models.CharField(max_length=500)
    parrafo6_seccion11 = models.CharField(max_length=2000)
    img_tabla_seccion11 = models.ImageField(blank=True, null=True)

    img_seccion12 = models.ImageField(blank=True, null=True)
    ref_img_seccion12 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion12 = models.CharField(max_length=500)
    parrafo1_seccion12 = models.CharField(max_length=2000)
    subtitulo2_seccion12 = models.CharField(max_length=500)
    parrafo2_seccion12 = models.CharField(max_length=2000)
    subtitulo3_seccion12 = models.CharField(max_length=500)
    parrafo3_seccion12 = models.CharField(max_length=2000)
    subtitulo4_seccion12 = models.CharField(max_length=500)
    parrafo4_seccion12 = models.CharField(max_length=2000)
    subtitulo5_seccion12 = models.CharField(max_length=500)
    parrafo5_seccion12 = models.CharField(max_length=2000)
    subtitulo6_seccion12 = models.CharField(max_length=500)
    parrafo6_seccion12 = models.CharField(max_length=2000)
    img_tabla_seccion12 = models.ImageField(blank=True, null=True)

    img_seccion13 = models.ImageField(blank=True, null=True)
    ref_img_seccion13 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion13 = models.CharField(max_length=500)
    parrafo1_seccion13 = models.CharField(max_length=2000)
    subtitulo2_seccion13 = models.CharField(max_length=500)
    parrafo2_seccion13 = models.CharField(max_length=2000)
    subtitulo3_seccion13 = models.CharField(max_length=500)
    parrafo3_seccion13 = models.CharField(max_length=2000)
    subtitulo4_seccion13 = models.CharField(max_length=500)
    parrafo4_seccion13 = models.CharField(max_length=2000)
    subtitulo5_seccion13 = models.CharField(max_length=500)
    parrafo5_seccion13 = models.CharField(max_length=2000)
    subtitulo6_seccion13 = models.CharField(max_length=500)
    parrafo6_seccion13 = models.CharField(max_length=2000)
    img_tabla_seccion13 = models.ImageField(blank=True, null=True)

    img_seccion14 = models.ImageField(blank=True, null=True)
    ref_img_seccion14 = models.CharField(max_length=70, blank=True, null=True)
    subtitulo1_seccion14 = models.CharField(max_length=500)
    parrafo1_seccion14 = models.CharField(max_length=2000)
    subtitulo2_seccion14 = models.CharField(max_length=500)
    parrafo2_seccion14 = models.CharField(max_length=2000)
    subtitulo3_seccion14 = models.CharField(max_length=500)
    parrafo3_seccion14 = models.CharField(max_length=2000)
    subtitulo4_seccion14 = models.CharField(max_length=500)
    parrafo4_seccion14 = models.CharField(max_length=2000)
    subtitulo5_seccion14 = models.CharField(max_length=500)
    parrafo5_seccion14 = models.CharField(max_length=2000)
    subtitulo6_seccion14 = models.CharField(max_length=500)
    parrafo6_seccion14 = models.CharField(max_length=2000)
    img_tabla_seccion14 = models.ImageField(blank=True, null=True)

    class Meta:
        verbose_name = 'Sendero'
        verbose_name_plural = 'Sendero'

    pass
